# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_text_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='text_response',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='Dashboard.Text'),
            preserve_default=False,
        ),
    ]
