# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_text_text_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Dashboard.Text'),
        ),
    ]
